flush ruleset

table inet meddefense {
    set DMZ {
        type ipv4_addr
        flags interval
        elements = { 10.0.10.0/24 }
    }
    set INTERNAL {
        type ipv4_addr
        flags interval
        elements = { 10.0.20.0/24 }
    }
    set MGMT {
        type ipv4_addr
        flags interval
        elements = { 10.0.30.0/24 }
    }
    set MEDDEV {
        type ipv4_addr
        flags interval
        elements = { 10.0.40.0/24 }
    }

    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        ip protocol icmp accept
        tcp dport 22 ip saddr @MGMT accept
        tcp dport 4242 ip saddr @MGMT accept
        tcp dport 3306 ip saddr @INTERNAL accept
        tcp dport 443 ip saddr @INTERNAL accept
        tcp dport 3306 ip saddr @DMZ accept
        tcp dport 4242 ip saddr @MEDDEV accept
        tcp dport 443 ip saddr @MEDDEV accept
        udp dport 53 accept
        tcp dport 53 accept
        log prefix "NFT-INPUT-DROP: " drop
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state established,related accept
        ip saddr @MGMT ip daddr @INTERNAL tcp dport 22 accept
        ip saddr @MGMT ip daddr @DMZ tcp dport 22 accept
        log prefix "NFT-FWD-DROP: " drop
    }

    chain output {
        type filter hook output priority 0; policy accept;
        ip daddr @MEDDEV drop
        log prefix "NFT-OUT-DROP: " drop
    }
}
